array.push
array.unshift(element)
array.pop
array.pop(element)
array.shift 
array.shift(element)
array.concat
array.insert(element)
array.uniq(element)
array.flatten(element)
array.delete(element)
array.delete_at(0)